/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReputationRouteImport } from './routes/api/reputation'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReputationRoute = ApiReputationRouteImport.update({
  id: '/api/reputation',
  path: '/api/reputation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/intelligence': typeof IntelligenceRoute
  '/leaderboard': typeof LeaderboardRoute
  '/settings': typeof SettingsRoute
  '/api/reputation': typeof ApiReputationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/intelligence': typeof IntelligenceRoute
  '/leaderboard': typeof LeaderboardRoute
  '/settings': typeof SettingsRoute
  '/api/reputation': typeof ApiReputationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/intelligence': typeof IntelligenceRoute
  '/leaderboard': typeof LeaderboardRoute
  '/settings': typeof SettingsRoute
  '/api/reputation': typeof ApiReputationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzer'
    | '/dashboard'
    | '/developer'
    | '/intelligence'
    | '/leaderboard'
    | '/settings'
    | '/api/reputation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzer'
    | '/dashboard'
    | '/developer'
    | '/intelligence'
    | '/leaderboard'
    | '/settings'
    | '/api/reputation'
  id:
    | '__root__'
    | '/'
    | '/analyzer'
    | '/dashboard'
    | '/developer'
    | '/intelligence'
    | '/leaderboard'
    | '/settings'
    | '/api/reputation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzerRoute: typeof AnalyzerRoute
  DashboardRoute: typeof DashboardRoute
  DeveloperRoute: typeof DeveloperRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SettingsRoute: typeof SettingsRoute
  ApiReputationRoute: typeof ApiReputationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reputation': {
      id: '/api/reputation'
      path: '/api/reputation'
      fullPath: '/api/reputation'
      preLoaderRoute: typeof ApiReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzerRoute: AnalyzerRoute,
  DashboardRoute: DashboardRoute,
  DeveloperRoute: DeveloperRoute,
  IntelligenceRoute: IntelligenceRoute,
  LeaderboardRoute: LeaderboardRoute,
  SettingsRoute: SettingsRoute,
  ApiReputationRoute: ApiReputationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
